# Generated by Django 3.1.7 on 2021-02-22 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empolyee',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=250)),
                ('emp_email', models.EmailField(max_length=254)),
                ('emp_contact', models.IntegerField()),
                ('emp_gender', models.CharField(max_length=10)),
                ('emp_dob', models.DateField()),
            ],
        ),
    ]
